apiVersion: v1
kind: Pod
metadata:
  name: api-pod
  labels:
    app: cloud-api
spec:
  containers:
    - image: cloud_api
      name: cloud-api-c
      imagePullPolicy: Never
      ports:
        - containerPort: 8000
          name: http
          protocol: TCP
      envFrom:
        - secretRef:
            name: mysecrets
      livenessProbe:
        httpGet:
          path: /docs
          port: 8000
        initialDelaySeconds: 5
        timeoutSeconds: 1
        periodSeconds: 10
        failureThreshold: 3
