apiVersion: v1
kind: Service
metadata:
  name: api-service
spec:
  type: NodePort
  selector:
    app: cloud-api
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
      nodePort: 30001
