apiVersion: v1
kind: Service
metadata:
  name: evento-service
spec:
  type: NodePort
  selector:
    app: evento
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30002
