apiVersion: v1
kind: Pod
metadata:
  name: evento-pod
  labels:
    app: evento
spec:
  containers:
    - image: evento_frontend
      name: evento-c
      imagePullPolicy: Never
      ports:
        - containerPort: 8080
          name: http
          protocol: TCP
      envFrom:
        - secretRef:
            name: mysecrets-frontend
      livenessProbe:
        httpGet:
          path: /
          port: 8080
        initialDelaySeconds: 5
        timeoutSeconds: 1
        periodSeconds: 10
        failureThreshold: 3
